name: ROCKs Organization Workflow

on:
  push:
    branches:
      - trunk
  repository_dispatch:
    types: [org-workflow-bot]

env:
  TOKEN: "${{ github.ref_name == 'trunk' && secrets.SERVICE_ACCOUNT_PAT || github.event.client_payload.token }}"
  SHA: "${{ github.ref_name == 'trunk' && 'channels/1.0/edge' || github.event.client_payload.sha }}"
  REPOSITORY: "${{ github.ref_name == 'trunk' && 'cjdcordeiro-new-test/mock-rock' || github.event.client_payload.repository.full_name }}"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.SHA }}
          token: ${{ env.TOKEN }}
      - run: ls
  send-report-to-rock:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: LouisBrunner/checks-action@v1.1.1
        if: env.REPOSITORY != 'ubuntu-rocks/mock-rock'  # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ env.TOKEN }}
          name: Test XYZ
          sha: ${{ env.SHA }}
          repo: ${{ env.REPOSITORY }}
          status: in_progress
          output: |
            {"summary": "foo"}
      - uses: LouisBrunner/checks-action@v1.1.1
        if: env.REPOSITORY != 'ubuntu-rocks/mock-rock'  # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ env.TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          sha: ${{ env.SHA }}
          repo: ${{ env.REPOSITORY }}
          status: completed
          output: |
            {"summary": "the end"}
      - uses: LouisBrunner/checks-action@v1.1.1
        if: env.REPOSITORY != 'ubuntu-rocks/mock-rock'  # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ env.TOKEN }}
          name: Test XYZ anith
          conclusion: ${{ job.status }}
          sha: ${{ env.SHA }}
          repo: ${{ env.REPOSITORY }}
          status: completed
          output: |
            {"summary": "the end 2"}
