name: ROCKs Organization Workflow

on:
  push:
    branches:
      - trunk
  repository_dispatch:
    types: [org-workflow-bot]

env:
  TOKEN: "${{ github.ref_name == 'trunk' && secrets.SERVICE_ACCOUNT_PAT || github.event.client_payload.token }}"
  SHA: "${{ github.ref_name == 'trunk' && 'channels/1.0/edge' || github.event.client_payload.sha }}"
  REPOSITORY: "${{ github.ref_name == 'trunk' && 'cjdcordeiro-new-test/mock-rock' || github.event.client_payload.repository.full_name }}"
  ROCK_NAME: "${{ github.ref_name == 'trunk' && 'mock-rock' || github.event.repository.name }}"

jobs:
  rocks-ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-outputs@v0.0.0-fake
        id: test
      - name: Checkout the ROCK repo (${{ env.REPOSITORY }})
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.SHA }}
          token: ${{ env.TOKEN }}
          submodules: 'recursive'
          # Default: fetch-depth = 1

      - name: Report the start of the ROCK CI/CD pipeline 
        uses: LouisBrunner/checks-action@v1.1.1
        continue-on-error: true   # Checks API does not work with PAT, only GH Apps
        id: checks-init
        with:
          token: ${{ env.TOKEN }}
          name: Running CI/CD for ROCK ${{ env.ROCK_NAME }}
          sha: ${{ env.SHA }}
          repo: ${{ env.REPOSITORY }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          status: in_progress
          output: |
            {"summary": "Building, testing and publishing a new ROCK revision for ${{ env.ROCK_NAME }}, based on the changes from ${{ env.SHA }}"}
      - uses: LouisBrunner/checks-action@v1.1.1
        continue-on-error: true   # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ env.TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          sha: ${{ env.SHA }}
          repo: ${{ env.REPOSITORY }}
          status: completed
          output: |
            {"summary": "the end"}
      - uses: LouisBrunner/checks-action@v1.1.1
        continue-on-error: true   # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ env.TOKEN }}
          name: Test XYZ anith
          conclusion: ${{ job.status }}
          sha: ${{ env.SHA }}
          repo: ${{ env.REPOSITORY }}
          status: completed
          output: |
            {"summary": "the end 2"}
