name: ROCKs Organization Workflow

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      name:
        required: true
        type: string
      full_name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  rocks-ci-cd-pipeline:
    name: ROCK CI/CD pipeline
    runs-on: ubuntu-latest
    steps:
      # Get the ROCK commit that triggered this run
      - name: Checkout the ROCK repo (${{ inputs.full_name }})
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.full_name }}
          ref: ${{ inputs.sha }}
          token: ${{ secrets.token }}
          submodules: 'recursive'
          # Default: fetch-depth = 1

      # Announce to the ROCK commit that a build is starting
      - name: Report the start of the ROCK CI/CD pipeline 
        uses: LouisBrunner/checks-action@v1.1.1
        continue-on-error: true   # Checks API does not work with PAT, only GH Apps
        id: checks-init
        with:
          token: ${{ secrets.token }}
          name: Running CI/CD for ROCK ${{ inputs.name }}
          sha: ${{ inputs.sha }}
          repo: ${{ inputs.full_name }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          status: in_progress
          output: |
            {"summary": "Building, testing and publishing a new ROCK revision for ${{ inputs.name }}, based on the changes from ${{ inputs.sha }}"}

      # Get the ROCK CI/CD pipeline scripts
      - name: Checkout the ROCK CI/CD pipelines repository
        uses: actions/checkout@v3
        with:
          repository: ubuntu-rocks/rocks-pipelines
          ref: rocks-ci   # TODO: main
          token:    # TODO may not need: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          submodules: 'recursive'
          path: rocks-pipelines
          # Default: fetch-depth = 1

      - name: Prepare environment to run ROCKs CI/CD pipelines
        run: pip install -r ./rocks-pipelines/src/rocks/requirements.txt

      # Run ROCK preflight checks
      - name: Run preflight checks
        id: preflight-checks 
        run: ./rocks-pipelines/src/rocks/Preflight-Checks.sh

      # Announce the preflight checks have finished
      - name: Report that preflight checks have ended 
        uses: LouisBrunner/checks-action@v1.1.1
        continue-on-error: true   # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ secrets.token }}
          name: Preflight checks completed for ${{ inputs.name }}
          sha: ${{ inputs.sha }}
          repo: ${{ inputs.full_name }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          output: |
            {"summary": "Preflight checks have completed with: ${{ steps.preflight-checks.outcome }}"}

      # -----------------------------------------------------
      # Announce to the ROCK commit that a build has finished
      - name: Report the end of the ROCK CI/CD pipeline 
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        continue-on-error: true   # Checks API does not work with PAT, only GH Apps
        with:
          token: ${{ secrets.token }}
          check_id: ${{ steps.checks-init.outputs.check_id }}
          sha: ${{ inputs.sha }}
          repo: ${{ inputs.full_name }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          status: completed
          conclusion: ${{ job.status }}

  # # Wrap-up job
  # wrap-up:
  #   name: Wrap up after ROCK CI/CD pipeline execution
  #   needs: rocks-ci-cd-pipeline
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: 