name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  call-workflow-passing-data:
    uses: cjdcordeiro-new-test/test-repo1/pipeline.yml@main
    with:
      username: mona
      secrets: inherit
