name: sched

on: [push]

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env:
          TOKEN: ${{ steps.get_token.outputs.app_token }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: cjdc
          client-payload: '{"name": "mock-rock", "full_name": "cjdcordeiro-new-test/mock-rock", "token": "${{ steps.get_token.outputs.app_token }}", "sha": "03b0b87fb0879276dc47248d1674fd6244ea8008"}'
