name: Reusable workflow example

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
      token:
        required: true
        type: string

env:
      SUPER_SECRET: ${{ secrets.token_from_settings }}

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
        
  call-workflow-passing-data:
    uses: cjdcordeiro-new-test/test-repo1/.github/workflows/pipeline.yml@main
    with:
      username: ${{ inputs.username }}
      token_input: ${{ inputs.token }}
    secrets:
      token: ${SUPER_SECRET}
